server:
  port: 5086

spring:
  application:
    name: dota2-analyzer

analyzer:
  cache-only: false
  disable-benchmarks: false
  avoid-external-when-cached: true
  permanent-accounts:
    - 237390446
  db:
    url: ${ANALYZER_DB_URL:jdbc:mysql://localhost:3306/dota2analyzer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    user: ${ANALYZER_DB_USER:root}
    password: ${ANALYZER_DB_PASSWORD:dota2analyzer}

logging:
  level:
    com.dota2analyzer: INFO
    org.springframework.web: INFO
